HOPSWORKS_API_KEY = "kRnWEgE1M5U0gKn9.qy4CzzuyaV4QQtppecDIi2Ee5oCnIKCdeRQd3DA6BPGQsEb97GFewhoJaCJj4Hkz"
HOPSWORKS_PROJECT = "pearls-aqi-predictor"
HOPSWORKS_USERNAME = "Mubashir Rehman"
HOPSWORKS_PASSWORD = ""
